# Generated by Django 4.0.10 on 2023-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_exam_question',
            field=models.BooleanField(default=False),
        ),
    ]
