# Generated by Django 4.0.10 on 2023-08-02 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
