# Generated by Django 4.0.10 on 2023-08-03 11:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_section_value'),
        ('questions', '0004_alter_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_exam_question',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(default='')),
                ('explanation', ckeditor.fields.RichTextField(default='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_options', to='questions.question')),
            ],
        ),
    ]
