# Generated by Django 4.0.10 on 2023-08-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_section_value'),
        ('questions', '0005_remove_exam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choose_from',
            field=models.CharField(choices=[('ALL', 'All'), ('COURSE', 'Course'), ('THEME', 'Theme')], default='ALL', max_length=6),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.theme'),
        ),
    ]
