# Generated by Django 4.0.10 on 2023-08-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.departmenthead'),
        ),
        migrations.AddField(
            model_name='department',
            name='instructors',
            field=models.ManyToManyField(related_name='departments', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.theme'),
        ),
    ]
