# Generated by Django 4.0.10 on 2023-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
